// BLOGS
export const FETCHING_BLOGS = 'FETCHING_BLOGS';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_ERROR = 'FETCH_BLOGS_ERROR';
// TODO - CRUD actions 
/*
  CREATE_BLOG = 'CREATE_BLOG';
  SUCCESS = 'SUCCESS';
  UPDATE_BLOG = 'UPDATE_BLOG';
  DELETE_BLOG = 'DELETE_BLOG';
*/